/**:
  ros__parameters:
    wheelbase: 0.33
    scan_topic: 'scan'
    odometry_topic: 'vesc/odom'

urg_node:
  ros__parameters:
    angle_max: 3.14
    angle_min: -3.14
    ip_address: "192.168.0.10"
    ip_port: 10940
    laser_frame_id: "laser"
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: true
    publish_multiecho: false
    cluster: 1
    skip: 0

vesc/**:
  ros__parameters:
    port: "/dev/ttyACM0"
    publish_tf: false
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 100.0
    current_min: 0.0
    duty_cycle_max: 0.0
    duty_cycle_min: 0.0
    position_max: 0.0
    position_min: 0.0
    servo_max: 1.0 #0.88497
    servo_min: 0.0 #0.08497
    speed_max: 45968.0  #23250
    speed_min: -45968.0
    #이론적인 07.07 erpm: 2873.0
    #수정 전 speed_to_erpm_gain: 2840.0
    speed_to_erpm_gain: 2873.0 #0716 2873.0 #0717 erpm 게인 수정, 본인 속도를 빠르다 생각해서 게인 높여줌, 그 결과 고속에서 로컬라이제이션 시 선속도 일치하게 됨
    speed_to_erpm_offset: 0.0
    steering_angle_to_servo_gain: 0.49
    #수정 전 steering_angle_to_servo_offset: 0.475 오른쪽으로 가는 경향이 심했음 0.48497
    steering_angle_to_servo_offset: 0.47892 #07.15 수정
    use_servo_cmd_to_calc_angular_velocity: true