state_machine:
  ros__parameters:
    rate: 80
    n_loc_wpnts: 80
    timetrials_only: false
    sim: true
    measure: false
    racecar_version: CAR
    ot_planner: lane_change
    track_length: 1.0
    gb_ego_width_m: 0.4
    gb_horizon_m: 15.0
    interest_horizon_m: 20.0
    gb_dynamic_trailing_distance_m: 10.0
    overtaking_horizon_m: 6.9
    emergency_break_horizon: 0.5
    volt_threshold: 14.5
    lateral_width_gb_m: 0.3
    lateral_width_ot_m: 0.3
    splini_hyst_timer_sec: 0.7
    splini_ttl: 2.0
    pred_splini_ttl: 2.0
    overtaking_ttl_sec: 2.0
    overtake_min_closing_mps: 2.5
    ftg_speed_mps: 2.0  #기존 0.1
    ftg_timer_sec: 0.01  #기존 3.0
    ftg_active: false
    offroad_distance_m: 4.0      # 차량에서 정적 trailing target의 앞면(s_start)까지 진입 거리 [m]
    offroad_active: true
    dwa_active: false             # OFFROAD와 같은 조건에서 DWAONLY 진입; 둘 다 true이면 DWA 우선
    force_GBTRACK: false
    use_force_trailing: false
    save_params: false
