"""One ROS-to-DWA parameter map shared by both controller managers."""

DWA_PARAM_MAP = {
    "dwa_min_speed_mps": "min_speed_mps",
    "dwa_max_speed_mps": "max_speed_mps",
    "dwa_max_accel_mps2": "max_accel_mps2",
    "dwa_max_decel_mps2": "max_decel_mps2",
    "dwa_max_steer_rad": "max_steer_rad",
    "dwa_max_steer_rate_radps": "max_steer_rate_radps",
    "dwa_velocity_resolution_mps": "velocity_resolution_mps",
    "dwa_steer_resolution_rad": "steer_resolution_rad",
    "dwa_predict_time_s": "predict_time_s",
    "dwa_prediction_dt_s": "prediction_dt_s",
    "dwa_dynamic_window_dt_s": "dynamic_window_dt_s",
    "dwa_wheelbase_m": "wheelbase_m",
    "dwa_goal_lookahead_m": "goal_lookahead_m",
    "dwa_heading_weight": "heading_weight",
    "dwa_obstacle_weight": "obstacle_weight",
    "dwa_velocity_weight": "velocity_weight",
    "dwa_safety_radius_m": "safety_radius_m",
    "dwa_obstacle_cost_scale_m": "obstacle_cost_scale_m",
    "dwa_vehicle_front_m": "vehicle_front_m",
    "dwa_vehicle_rear_m": "vehicle_rear_m",
    "dwa_vehicle_width_m": "vehicle_width_m",
    "dwa_collision_margin_m": "collision_margin_m",
    "dwa_scan_min_range_m": "scan_min_range_m",
    "dwa_scan_max_range_m": "scan_max_range_m",
    "dwa_lidar_offset_x_m": "lidar_offset_x_m",
    "dwa_lidar_offset_y_m": "lidar_offset_y_m",
    "dwa_lidar_yaw_rad": "lidar_yaw_rad",
}
